usernames:
  bhamm:
    email: bh@gmail.com
    name: brandi
    password: $2b$12$1Gbu3ZKEqKUdM9F8qROe7ORUFemrX6UeU0ipwEA3UNPI9TrjHx/wO
  ejones:
    email: U57255@gmail.com
    name: U57255
    password: $2b$12$BsFToucSwGpFwm9jRRxExe.YrKghgmFPHv001VCaYUlsf90jPZSlS
  jsmith:
    email: jsmith@gmail.com
    name: U25497
    password: $2b$12$AeGpCRYNEyd65rXFsYxG5uAyBBILwC/KkA2.lea9gFqbsWZw0/L8e
