usernames:
  bhammin:
    email: bh@gmail.com
    name: Brandi
    password: $2b$12$PKTIAL6PeshcieMKbwIwm.zf9/gEhWwjAK0.nd.cDLf6O0vAOpVZG
  ejones:
    email: U57255@gmail.com
    name: U57255
    password: $2b$12$BsFToucSwGpFwm9jRRxExe.YrKghgmFPHv001VCaYUlsf90jPZSlS
  jsmith:
    email: jsmith@gmail.com
    name: U25497
    password: $2b$12$AeGpCRYNEyd65rXFsYxG5uAyBBILwC/KkA2.lea9gFqbsWZw0/L8e
